name: CI/CD Pipeline Taller Automotriz

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- Trabajo para el Frontend ---
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./taller-frontend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm' 
        cache-dependency-path: taller-frontend/package-lock.json

    - name: Instalar dependencias
      run: npm install

    - name: Linting
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Tests
      run: echo "No hay tests definidos para el frontend"
  # --- Trabajo para el Backend ---
  backend:
    name: Backend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Instalar dependencias
      run: npm install
    
    - name: Initialize Database
      run: node scripts/create-db.js
      
    - name: Linting
      run: npm run lint

    - name: Tests
      run: npm test
